spring.application.name=users
server.port=8081

# PostgreSQL BBDD
spring.datasource.url=jdbc:postgresql://localhost:5432/usersSecGest
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:apertura15}

# Configuracion de Hibernate (gestion de la base de datos)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# Seguridad JWT
jwt.secret=${JWT_SECRET:0123456789ABCDEFGHIJKLMNOPQRSTUV}
jwt.expirationMs=86400000

# Parametros del admin
app.admin.username=isabel
app.admin.password=123456

app.cors.allowed-origins=http://localhost:4200